function execute() {
    return Response.success([
        { "title": "Action", "input": "/action/", "script": "zen.js" },
        { "title": "Adventure", "input": "/adventure/", "script": "zen.js" },
        { "title": "Comedy", "input": "/comedy/", "script": "zen.js" },
        { "title": "Drama", "input": "/drama/", "script": "zen.js" },
        { "title": "School Life", "input": "/school-life/", "script": "zen.js" },
        { "title": "Shoujo", "input": "/shoujo/", "script": "zen.js" },
        { "title": "Shounen", "input": "/shounen/", "script": "zen.js" },
        { "title": "Anime", "input": "/anime/", "script": "zen.js" },
        { "title": "Comic", "input": "/comic/", "script": "zen.js" },
        { "title": "Cooking", "input": "/cooking/", "script": "zen.js" },
        { "title": "Doujinshi", "input": "/doujinshi/", "script": "zen.js" },
        { "title": "Ecchi", "input": "/ecchi/", "script": "zen.js" },
        { "title": "Fantasy", "input": "/fantasy/", "script": "zen.js" },
        { "title": "Gender Bender", "input": "/gender-bender/", "script": "zen.js" },
        { "title": "Harem", "input": "/harem/", "script": "zen.js" },
        { "title": "Historical", "input": "/historical/", "script": "zen.js" },
        { "title": "Horror", "input": "/horror/", "script": "zen.js" },
        { "title": "Josei", "input": "/josei/", "script": "zen.js" },
        { "title": "Live action", "input": "/live-action/", "script": "zen.js" },
        { "title": "Martial Arts", "input": "/martial-arts/", "script": "zen.js" },
        { "title": "Mature", "input": "/mature/", "script": "zen.js" },
        { "title": "Mecha", "input": "/mecha/", "script": "zen.js" },
        { "title": "Mystery", "input": "/mystery/", "script": "zen.js" },
        { "title": "One shot", "input": "/one-shot/", "script": "zen.js" },
        { "title": "Psychological", "input": "/psychological/", "script": "zen.js" },
        { "title": "Sci-fi", "input": "/sci-fi/", "script": "zen.js" },
        { "title": "Seinen", "input": "/seinen/", "script": "zen.js" },
        { "title": "Shoujo Ai", "input": "/shoujo-ai/", "script": "zen.js" },
        { "title": "Shounen Ai", "input": "/shounen-ai/", "script": "zen.js" },
        { "title": "Slice of Life", "input": "/slice-of-life/", "script": "zen.js" },
        { "title": "Smut", "input": "/smut/", "script": "zen.js" },
        { "title": "Soft Yaoi", "input": "/soft-yaoi/", "script": "zen.js" },
        { "title": "Soft Yuri", "input": "/soft-yuri/", "script": "zen.js" },
        { "title": "Sports", "input": "/sports/", "script": "zen.js" },
        { "title": "Tragedy", "input": "/tragedy/", "script": "zen.js" },
        { "title": "Supernatural", "input": "/supernatural/", "script": "zen.js" },
        { "title": "Webtoon", "input": "/webtoon/", "script": "zen.js" },
        { "title": "Yaoi", "input": "/yaoi/", "script": "zen.js" },
        { "title": "Yuri", "input": "/yuri/", "script": "zen.js" }
    ])}