function execute() {
    return Response.success([
        { "title": "Action", "input": "/action/", "script": "zen.js" },
        { "title": "Adventure", "input": "/adventure/", "script": "zen.js" },
        { "title": "Billionaire", "input": "/billionaire/", "script": "zen.js" },
        { "title": "Boys Love", "input": "/boys-love-290822/", "script": "zen.js" },
        { "title": "Celebrity", "input": "/celebrity/", "script": "zen.js" },
        { "title": "Comedy", "input": "/comedy/", "script": "zen.js" },
        { "title": "Dark Fantasy", "input": "/dark-fantasy/", "script": "zen.js" },
        { "title": "Drama", "input": "/drama-rln2/", "script": "zen.js" },
        { "title": "Ecchi", "input": "/ecchi/", "script": "zen.js" },
        { "title": "Fantasy", "input": "/fantasy/", "script": "zen.js" },
        { "title": "Games", "input": "/games/", "script": "zen.js" },
        { "title": "Gender Bender", "input": "/gender-bender/", "script": "zen.js" },
        { "title": "Harem", "input": "/harem-290822/", "script": "zen.js" },
        { "title": "Historical", "input": "/historical/", "script": "zen.js" },
        { "title": "Horror", "input": "/horror/", "script": "zen.js" },
        { "title": "Isekai", "input": "/isekai/", "script": "zen.js" },
        { "title": "Josei", "input": "/josei-010722/", "script": "zen.js" },
        { "title": "LitRPG", "input": "/litrpg/", "script": "zen.js" },
        { "title": "Magic", "input": "/magic/", "script": "zen.js" },
        { "title": "Magical Realism", "input": "/magical-realism-rln2/", "script": "zen.js" },
        { "title": "Martial Arts", "input": "/martial-arts-rln/", "script": "zen.js" },
        { "title": "Mature", "input": "/mature-rln/", "script": "zen.js" },
        { "title": "Mecha", "input": "/mecha-290822/", "script": "zen.js" },
        { "title": "Military", "input": "/military-290822/", "script": "zen.js" },
        { "title": "Modern Life", "input": "/modern-life/", "script": "zen.js" },
        { "title": "Mystery", "input": "/mystery/", "script": "zen.js" },
        { "title": "Psychological", "input": "/psychological/", "script": "zen.js" },
        { "title": "Recarnation", "input": "/recarnation-290822/", "script": "zen.js" },
        { "title": "Romance", "input": "/romance/", "script": "zen.js" },
        { "title": "School Life", "input": "/school-life/", "script": "zen.js" },
        { "title": "Sci-fi", "input": "/sci-fi/", "script": "zen.js" },
        { "title": "Seinen", "input": "/seinen/", "script": "zen.js" },
        { "title": "Shotacon", "input": "/shotacon/", "script": "zen.js" },
        { "title": "Shoujo", "input": "/shoujo/", "script": "zen.js" },
        { "title": "Shoujo Ai", "input": "/shoujo-ai/", "script": "zen.js" },
        { "title": "Shounen", "input": "/shounen/", "script": "zen.js" },
        { "title": "Shounen Ai", "input": "/shounen-ai-rln/", "script": "zen.js" },
        { "title": "Slice of Life", "input": "/slice-of-life/", "script": "zen.js" },
        { "title": "Smut", "input": "/smut/", "script": "zen.js" },
        { "title": "Sports", "input": "/sports/", "script": "zen.js" },
        { "title": "Supernatural", "input": "/supernatural/", "script": "zen.js" },
        { "title": "Tragedy", "input": "/tragedy/", "script": "zen.js" },
        { "title": "Urban Life", "input": "/urban-life/", "script": "zen.js" },
        { "title": "Urban Life", "input": "/urban-life-urban-life/", "script": "zen.js" },
        { "title": "Virtual Reality", "input": "/virtual-reality-290822/", "script": "zen.js" },
        { "title": "War", "input": "/war-290822/", "script": "zen.js" },
        { "title": "Wuxia", "input": "/wuxia/", "script": "zen.js" },
        { "title": "Xianxia", "input": "/xianxia-290822/", "script": "zen.js" },
        { "title": "Xuanhuan", "input": "/xuanhuan/", "script": "zen.js" },
        { "title": "Yaoi", "input": "/yaoi/", "script": "zen.js" },
        { "title": "Yuri", "input": "/yuri/", "script": "zen.js" }
    ]);
}